# -*- coding: utf-8 -*-
"""Aula08.IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-r3Zimb1uHQJ9rCpmFJxEKYIEBxCErt1
"""

import os
import shutil
import tempfile

# Dicionário que mapeia extensões de arquivo para nomes de pastas
# Você pode adicionar mais tipos conforme necessário
TIPOS_DE_ARQUIVOS = {
    '.pdf': 'Documentos PDF',
    '.doc': 'Documentos Word',
    '.docx': 'Documentos Word',
    '.xls': 'Planilhas Excel',
    '.xlsx': 'Planilhas Excel',
    '.ppt': 'Apresentações PowerPoint',
    '.pptx': 'Apresentações PowerPoint',
    '.png': 'Imagens PNG',
    '.jpg': 'Imagens JPG',
    '.jpeg': 'Imagens JPEG',
    '.gif': 'Imagens GIF',
    '.txt': 'Arquivos de Texto',
    '.zip': 'Arquivos Compactados',
    '.rar': 'Arquivos Compactados',
    '.mp3': 'Músicas',
    '.wav': 'Músicas',
    '.mp4': 'Vídeos',
    '.avi': 'Vídeos',
    '.mov': 'Vídeos',
    '.py': 'Scripts Python',
    '.ipynb': 'Notebooks Jupyter'
}

def organizar_arquivos(diretorio_origem='.'):
    """
    Organiza arquivos em pastas baseadas em suas extensões no diretório especificado.
    Cria pastas para tipos de documentos comuns (.pdf, .doc, .xls, .png, etc.)
    e move os arquivos para elas. Funciona sem permissões de administrador
    desde que o diretorio_origem seja acessível ao usuário.
    """

    print(f"\nIniciando organização de arquivos em: {os.path.abspath(diretorio_origem)}")

    # Itera sobre todos os itens no diretório de origem
    for nome_arquivo in os.listdir(diretorio_origem):
        caminho_completo_arquivo = os.path.join(diretorio_origem, nome_arquivo)

        # Ignora diretórios
        if os.path.isdir(caminho_completo_arquivo):
            continue

        # Obtém a extensão do arquivo em minúsculas
        _, extensao = os.path.splitext(nome_arquivo)
        extensao = extensao.lower()

        # Verifica se a extensão está no nosso dicionário de tipos
        if extensao in TIPOS_DE_ARQUIVOS:
            nome_pasta = TIPOS_DE_ARQUIVOS[extensao]
        else:
            # Se não for um tipo conhecido, coloca em uma pasta 'Outros'
            nome_pasta = 'Outros'

        # Define o caminho completo para a pasta de destino
        caminho_pasta_destino = os.path.join(diretorio_origem, nome_pasta)

        # Cria a pasta de destino se ela não existir
        if not os.path.exists(caminho_pasta_destino):
            os.makedirs(caminho_pasta_destino)
            print(f"Pasta '{nome_pasta}' criada.")

        # Define o caminho completo do arquivo no destino
        caminho_destino_arquivo = os.path.join(caminho_pasta_destino, nome_arquivo)

        try:
            # Move o arquivo para a pasta de destino
            shutil.move(caminho_completo_arquivo, caminho_destino_arquivo)
            print(f"Arquivo '{nome_arquivo}' movido para '{nome_pasta}'.")
        except Exception as e:
            print(f"Erro ao mover o arquivo '{nome_arquivo}': {e}")

    print("Organização de arquivos concluída!")


def criar_arquivos_teste(diretorio_origem, tipos_de_arquivos_dict, num_arquivos_por_extensao=3):
    """
    Cria arquivos de teste no diretório especificado para simular a organização.
    """
    print(f"\nCriando {num_arquivos_por_extensao} arquivos de teste para cada extensão em: {diretorio_origem}")
    for extensao in tipos_de_arquivos_dict.keys():
        for i in range(1, num_arquivos_por_extensao + 1):
            nome_arquivo = f"arquivo_teste_{i}{extensao}"
            caminho_arquivo = os.path.join(diretorio_origem, nome_arquivo)
            with open(caminho_arquivo, 'w') as f:
                f.write(f"Conteúdo de teste para {nome_arquivo}")
            print(f"Criado: {nome_arquivo}")

# --- EXECUTAR O SCRIPT --- Com simulação de arquivos de teste
print("O diretório de trabalho atual é: " + os.getcwd())

temp_dir = None
try:
    # Cria um diretório temporário para a simulação
    temp_dir = tempfile.mkdtemp()
    print(f"Diretório temporário para simulação criado: {temp_dir}")

    # Cria arquivos de teste no diretório temporário
    criar_arquivos_teste(temp_dir, TIPOS_DE_ARQUIVOS, num_arquivos_por_extensao=3)

    # Executa a organização dos arquivos no diretório temporário
    organizar_arquivos(temp_dir)

except Exception as e:
    print(f"Ocorreu um erro durante a simulação: {e}")
finally:
    # Limpa o diretório temporário
    if temp_dir and os.path.exists(temp_dir):
        shutil.rmtree(temp_dir)
        print(f"\nDiretório temporário '{temp_dir}' e seu conteúdo foram removidos.")

import requests

def buscar_endereco(cep: str):
    """
    Consome a API ViaCEP e processa os dados de forma estruturada.
    """
    # Sanitização: Remove tudo que não for número
    cep_limpo = "".join(filter(str.isdigit, cep))

    if len(cep_limpo) != 8:
        return {"erro": "CEP inválido. Certifique-se de digitar 8 números."}

    url = f"https://viacep.com.br/ws/{cep_limpo}/json/"

    try:
        response = requests.get(url, timeout=5) # Timeout evita que o código trave
        response.raise_for_status()
        dados = response.json()

        if "erro" in dados:
            return {"erro": f"O CEP {cep_limpo} não foi localizado na base de dados."}

        # Criamos um dicionário organizado com o que realmente importa
        resultado = {
            "rua": dados.get("logradouro"),
            "bairro": dados.get("bairro"),
            "cidade": dados.get("localidade"),
            "estado": dados.get("uf"),
            "codigo_ibge": dados.get("ibge"),
            "regiao": dados.get("regiao", "N/A") # Informação nova da API ViaCEP
        }

        return resultado

    except requests.exceptions.HTTPError as e:
        return {"erro": f"Erro de servidor: {e}"}
    except Exception as e:
        return {"erro": f"Falha na conexão: {e}"}

# --- Interface de exibição amigável ---

def exibir_resultado(res):
    if "erro" in res:
        print(f"{res['erro']}")
    else:
        print(f"Endereço Encontrado:")
        for chave, valor in res.items():
            print(f"   {chave.title()}: {valor}")

# --- Testes ---

testes = ["01001000", "70002-900", "00000000", "abc12345"]

for t in testes:
    print(f"\nConsultando: {t}")
    resultado = buscar_endereco(t)
    exibir_resultado(resultado)
    print("-" * 20)